Numpy  arrays and the different libraries

In [4]:
import numpy as np
arr = np.array([ [1,2,3], [2,3,4]])
arr


(2, 3)

In [5]:
arr.shape # returns a tuple containing the number of rows and
# colums 

(2, 3)

In [6]:
# the dimension is retrieved using 
arr.ndim # returns an integer indicating the dimension

2

In [7]:
arr.dtype # returns the data type and if there is one float 
# it would return float 
# the int64 means the bit is 64 integers and can be restricted 
# if the need arises

dtype('int64')

In [12]:
# the nd array can also be created using the arange function
# which has start stop and step and works similary to range in python
# but returns a nd array

import numpy as np
import timeit
arr = np.arange(1000)
print(" this is np",timeit.timeit(lambda:2* arr, number = 10000))
mylist = []
for i in range(1000):
    mylist.append(i)
print("this is list",timeit.timeit(lambda: 2 *mylist, number = 10000))

# numpy is faster approximately 250 faster than list and the difference
# is more visible for larger size

 this is np 0.030075030983425677
this is list 0.03896806400734931


Methods to create numpy arrays 

In [17]:
import numpy as np
arr = np.zeros([3,2,4], dtype = 'int32')
arr
# passing the shape of the array as a list is not a good practice because lists are mutable
# and since the arguments passed should not be changed it is a good practice to pass it as a tuple

newarr = np.zeros((3,2,4), dtype = 'int32')
newarr
# there is no specific reason for creating int 32
# and by default it creattes float64 of zeros 
# the reason for creating an array of zeros is so that it can be 
# filled depending on the need
onesarr = np.ones((3,2,4))
onesarr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

the functions zeros_like and ones_like is very useful when it comes to creating an array like an already created or given array. For example


In [18]:
import numpy as np 
arr  = np.array([[1,2,3], [3,2,1]])
np.zeros_like(arr)
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1]])

the function random.rand is useful when it comes to creating an array with random numbers
it takes the shape as an argument


In [19]:
import random
np.random.rand(2,3)

array([[0.14676531, 0.29737883, 0.55241723],
       [0.5530817 , 0.53564544, 0.6741871 ]])

Accessing elements of nd arrays 
 the index can be used to access a single element 
 a range can be specified 

In [21]:
arr = np.random.rand(3,2)
print(arr)
print("\n")
print(arr[0,1]) # using index to retrieve a single element
# zero represents the first row and 1 the second column

[[0.89354161 0.32525079]
 [0.28245682 0.82927491]
 [0.94364717 0.4674391 ]]


0.3252507922031349


In [22]:
# retrieving a range of elements
arr = np.random.rand(3,2)
print(arr, '\n')
print(arr[1:,:])  # 1: from the second row onwards 
# : means the full range or all onwards 


[[0.85896801 0.79984551]
 [0.65211866 0.59193932]
 [0.26130137 0.56183354]] 

[[0.65211866 0.59193932]
 [0.26130137 0.56183354]]


the values returned have different arrays and shapes and 
sometimes it is not an array if a single element is returned
fpr example

!! pay attention to the difference in synthax between 
arr[1:,:] and  the second : means full range after 1
arr[1,:] the : means on the same row only 

In [23]:
arr = np.random.rand(3,2)
print(arr, "\n")
print(arr[0,:]) # pay attention to the different synthax 


[[0.74787214 0.05174626]
 [0.09362276 0.30574278]
 [0.85117869 0.8066407 ]] 

[0.74787214 0.05174626]


Accessing the elements in the nd arrays using boolean values
The way it is done is that another list containing boolean values coresponding with how we want to prin the array is created ( true meaning element to be printed and false to be ignored) 

This method is useful when we have numerical facts about an entity stored in a nd array that have to be retrieved

In [24]:
arr = np.array([1,2,3,4])
lst = [True, False, False, True]
arr[lst]
# the values correspoding to True are printed

array([1, 4])

Nd arrays are mutable meaning the it's content can be modified using index and assignment or equal to the desired appropriate value. (appropriate because the dtype has to be observed)

In [27]:
arr = np.random.rand(4,3)
print(arr, '\n\n')
arr[1:3,:] = 1
print(arr)

[[0.5170931  0.70089746 0.53454424]
 [0.95616609 0.62224568 0.03525615]
 [0.16322275 0.46302817 0.6549629 ]
 [0.38506188 0.21376027 0.61369598]] 


[[0.5170931  0.70089746 0.53454424]
 [1.         1.         1.        ]
 [1.         1.         1.        ]
 [0.38506188 0.21376027 0.61369598]]


Operations for Numpy Arrays 
- Two arrays of the same size and shape can be added together 
- can be substracted from each other 
- can be multiplied
- and division can be applied
- and the elements in the same index are added or substracted and a new array of the same size and shape is returned 

- if either the size or shape is not the same, then a ValueError is returned with a messagae hinting on different shapes. 

In [32]:
import numpy as np
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.ones((2,4))
print(arr1,'\n')
print(arr1+arr2)
print(arr1-arr2)



[[1 2 3 4]
 [1 2 3 4]] 

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]]


## transpose 
- nd arrays can be transposed and it is performed using the T aatribute which returns a new nd array 
if an array with shape(2,3) and array with (3,2) is returned 

In [33]:
import numpy as np
arr1 =  np.random.rand(2,3)
print(arr1, '\n')
print(arr1.T)

[[0.6677226  0.81322963 0.41407847]
 [0.92276699 0.99144907 0.20778972]] 

[[0.6677226  0.92276699]
 [0.81322963 0.99144907]
 [0.41407847 0.20778972]]


# Matrix Multiplication
Multiplication is performed according to the rules of matrix multiplication 
- the infinix operator for matrix multiplication is `@`
-  @ though the shape might not match this @ symbol allows matrix braodcasting according to the numpy rules if the rows of the first array matches the column of th second one
then it can be rearanged so that the multiplation works

In [36]:
import numpy as np
arr1  = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,0,0], [0,2,0], [0,0,3]])
print(arr1,'\n')
print(arr2,'\n')
print(arr1@ arr2)


[[ 1  4  9]
 [ 4 10 18]]


## Advanced linear operations such as inverses and  determinants can be done on arrays ##


In [37]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(np.linalg.det(x), '\n')
print(np.linalg.inv(x), '\n')
print(x @np.linalg.inv(x))

-2.0000000000000004 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


Creating custom Numpy Array Functions 
- the built in operations for numpy are very efficient in speed 
- writing our own function using loops and other ineficient structures which numpy avoids is ineficient and therefore 
- to make it efficient 
## our custom functions have to be `universal` `ufunc` that they can act on numpy objects too ## 


`np.vectorize` is used to make a custom function efficient and suitable to work on numpy objects

`frompyfun` can also be used to adjust accordingly custom functions. this takes 
- the already defined python function as first argument 
- number of input arrays  as second argument
- number of returning arrays a third argument


In [43]:
import numpy as np
arr1 = np.array([[1,2], 
                 [3,4]])
arr2 = np.array([[4,3],
                 [2,1]])

def linear_comb(x,y):
    return 2 *x +y

np.vectorize(linear_comb)

linear_comb(arr1, arr2)

array([[6, 7],
       [8, 9]])

## input, output and Data visualization 

let's assume that we have a CSV file 
A csv file contains data arranged in rows and colums 
and the colums are separeted by `,` and the rows appear on each new line

In [44]:
with open('codinglabs.csv', 'w') as f:
    for k in range(-5,5):
        f.write("{:.1f},{:.2f}\n".format(k,k**2)) # this creates a new file 
    

To import the data into our numpy arrays 
`np.loadtxt` is used provided by numpy
- it takes many arguments but the most important one is the `delimiter` which is a comma `,`.

## if file has header as columns we obtain a ValueError such as pthon could not convert strings to floats because python reads numerical values as floats by default, if there is a need to read the values as a specific type then `dtype` could be passed to the ` np.loadtxt` ##

if the file has headers
- the function `np.load` is used and must be instructe to ignore first `n`lines using the optional argument and value `skiprows = n` 
- To specify the number of colums to be read, the optional argument `usecols = (1,2,4)` can be passed and would read only the ` 1,  2 and 4` colums.

- it is crucial to consider the delimiter used in the csv file as it changes and could be `TAB`, and`;`

In [45]:
arr = np.loadtxt("codinglabs.csv", delimiter = ',')
arr

array([[-5., 25.],
       [-4., 16.],
       [-3.,  9.],
       [-2.,  4.],
       [-1.,  1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

## Data ouput from a Numpy Array ##
- the function `np.savetxt` can be used to saved a numpy array into a file of desired name. but it saves it as human readable, if not human readable is desired then np.save can be used it takes
- the name of the file as the first argument 
- the array name from which the array is got from
- and many more optional arguments 


In [48]:
import numpy as np
array1= np.linspace(0,1,11)
np.savetxt("savingarrays", array1, fmt = "%.4f")
np.save("codingarray", array1) # save it as a binary file

## Data visualization uses Matplotlib see first semester notes ##